ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret             VARCHAR(256);
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_enabled            BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS backup_codes            TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_picture         VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE;
